apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uiuc-chat
  namespace: uiuc-chat
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chat.local
      secretName: uiuc-chat-tls
  rules:
    - host: chat.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uiuc-chat-frontend
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: uiuc-chat-frontend
                port:
                  number: 3000
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: uiuc-chat-backend
                port:
                  number: 8001
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: uiuc-chat-keycloak-http
                port:
                  number: 80

